[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x", "caddy"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --include=dev"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "NODE_ENV=production npx vite build --config vite.config.railway.ts"
]

[start]
cmd = "caddy run --config Caddyfile --adapter caddyfile"