[phases.build]
dependsOn = ["install"]
cmds = [
  "NODE_ENV=production npx vite build --config vite.config.railway.ts",
  "npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --external:@replit/* --external:pg-native --external:cpu-features --external:vite"
]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --include=dev"]

[phases.setup]
nixpkgs = ["nodejs-20_x", "npm-9_x"]

[start]
cmd = "node dist/index.js"