services:
  - type: web
    name: customer-service-platform
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: node scripts/render-start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: customer-service-platform
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: customer-service-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
    healthCheckPath: /api/health
    autoDeploy: false

databases:
  - name: customer-service-db
    databaseName: customer_service
    user: customer_service_user
    plan: starter